# Generated by Django 4.0.2 on 2022-02-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_article_text_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='numofarticle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blog.article'),
            preserve_default=False,
        ),
    ]
