# Generated by Django 4.0.2 on 2022-02-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_author_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='First_name',
            field=models.CharField(max_length=20, verbose_name='نام'),
        ),
    ]
