# Generated by Django 4.0.2 on 2022-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_author_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسنده\u200cها'},
        ),
        migrations.AlterField(
            model_name='author',
            name='Last_name',
            field=models.CharField(max_length=40, verbose_name='نام خانوادگی'),
        ),
    ]
