# Generated by Django 4.0.2 on 2022-02-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_author_options_alter_author_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='writer',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
